### ISSUE TITLE
RTNETLINK answers: Operation not supported

### ISSUE THREAD

**Issue by dtypo** [devplayer0/docker-net-dhcp#11]
Hello @devplayer0 :)
I'm trying to setup your Docker plugin to give an own IP to every container of mine.
The most tedious problem is that I'm running Docker on a Synology NAS (DS920+, so Intel Gemini Lake CPU), and the preinstalled network tools seem quite limited.
In particular, you guide give me error attaching the eth0 network card to the newly created bridge.
After som googling, seems that some kernel modules are lacking, but I'm not sure how to proceed (which modules? how to compile them correctly in a pretty "close" environemnt like a Syno NAS, without a proper package manager?)
Could you please give me an hand?
Thanks in advance :) 

```
root@DS:~#docker plugin install devplayer0/net-dhcp
Plugin "devplayer0/net-dhcp" is requesting the following privileges:
 - network: [host]
 - host pid namespace: [true]
 - mount: [/var/run/docker.sock]
 - capabilities: [CAP_NET_ADMIN CAP_SYS_ADMIN CAP_SYS_PTRACE CAP_SYS_RESOURCE]
Do you grant the above permissions? [y/N] Y
latest: Pulling from devplayer0/net-dhcp
f20d1e188e68: Download complete
Digest: sha256:fe6055ff762181da6a358dad689c6a8cfd5fa3687a3a1da9c4cec894eea6f41a
Status: Downloaded newer image for devplayer0/net-dhcp:latest
Installed plugin devplayer0/net-dhcp
root@DS:~# sudo ip link add dhcp-bridge type bridge
root@DS:~# sudo ip link set dhcp-bridge up
root@DS:~# sudo ip link set eth0 up
root@DS:~# sudo ip link set eth0 master dhcp-bridge
RTNETLINK answers: Operation not supported
```

**Comment by devplayer0** [comment]
Apologies for the much delayed response, I'm only coming back to working on this now! Definitely looks like a feature missing from the Synology kernel, unfortunately I've no experience with commercial NAS appliance so I'm not sure of the specifics for compiling and installing them to get this working :disappointed:
