### ISSUE TITLE
invalid rootfs in image configuration

### ISSUE THREAD

**Issue by Tone866** [devplayer0/docker-net-dhcp#16]
On Arm Devices (I tested it with 2 Pi's) I get the following error:
```
$ sudo docker plugin install ghcr.io/devplayer0/docker-net-dhcp:release-linux-arm-v7
Error response from daemon: invalid rootfs in image configuration

Jun 11 17:05:57 raspberrypi dockerd[463]: time="2021-06-11T17:05:57.310918436+02:00" level=info msg="Attempting next endpoint for pull after error: invalid rootfs in image configuration"
Jun 11 17:05:57 raspberrypi dockerd[463]: time="2021-06-11T17:05:57.311169098+02:00" level=error msg="Handler for GET /v1.39/plugins/privileges returned error: invalid rootfs in image configuration"
```
On an x86 machine it worked for me.

Pi 1: `Docker version 18.09.1, build 4c52b90`
Pi 2: `Docker version 19.03.15, build 99e3ed8919`
x86: `Docker version 20.10.7, build f0df350`

**Comment by devplayer0** [comment]
I ran into this issue on my `x86_64` machine but it was due to an outdated Docker version. Can you try upgrading Docker on your Pi(s)?

**Comment by Tone866** [comment]
Indeed with version 20 it works!
An information in the readme would be useful.
Thanks!

**Comment by devplayer0** [comment]
Nice :) I'll add a note to the README.
