### ISSUE TITLE
Can not create network

### ISSUE THREAD

**Issue by siaimes** [devplayer0/docker-net-dhcp#17]
````bash
$ sudo docker network create -d ghcr.io/devplayer0/docker-net-dhcp:release-linux-amd64 --ipam-driver null -o bridge=my-bridge my-dhcp-net
Error response from daemon: NetworkDriver.CreateNetwork: bridge already in use by Docker
```

**Comment by devplayer0** [comment]
Do you already have a network created using the plugin for that bridge? Only one network at a time can use a single bridge.

**Comment by siaimes** [comment]
> Do you already have a network created using the plugin for that bridge? Only one network at a time can use a single bridge.

Thank you for your reply, I get it.
